.Dd March 11, 2018
.Dt HFSINSPECT 1
.Os
.Sh NAME
.Nm hfsinspect
.Nd inspect disk structures for HFS+ volumes
.de Nn
Forthcoming.
..
.Sh SYNOPSIS
.Nm
.Op Fl hvDjlrSB
.Op Fl d Ar DEV | Fl V Ar VOLUME
.Op Fl sf0H Fl t Ar TOP
.Op Fl o Ar outpath
.Op Fl b Ar attributes | Ar catalog | Ar extents | Ar hotfiles
.Op Fl n Ar NNUM
.Op Fl T Ar TYPE
.Op Fl c Ar CNID | Fl F Ar parent:name
.Op Fl p Ar localpath | Fl P Ar virtualpath
.Op Fl y Ar DIR
.Op Fl i Ar STARTBLOCK:BLOCKCOUNT
.Sh DESCRIPTION
.Ss GENERAL
.Bl -tag -offset indent -width "123456789012345"
.It Fl h , Cm --help
Show help and quit.
.It Fl v , Cm --version
Show version information and quit.
.It Fl v , Cm --verbose
When combined with other options,
.Fl v
is interpreted to mean
.Fl -verbose,
which increases the verbosity of output of those options (see below).
.It Fl S , Cm --si
Use base 1000 SI data size measurements instead of the traditional base 1024.
.It Fl B , Cm --debug
Set to be overwhelmed with useless data.
.El
.Ss SOURCES
.Nm
will use the root filesystem by default, or the filesystem containing a target file in some cases. If you wish to
specify a specific device or volume, you can with the following options:
.Bl -tag -offset indent -width "123456789012345"
.It Fl d , Cm --device Ar DEV
Path to device or file containing an HFS+ filesystem. The source may be either a bare HFS+ filesystem or include a partition map (APT, MBR, or GPT), in which case
.Nm
will use the first HFS+ volume it finds.
.Nm
also fully supports HFSX (both case-preserving and case-sensitive modes) and HFS-wrapped HFS+ volumes.
.It Fl V , Cm --volume Ar VOLUME
Use the path to a mounted disk or any file on the disk to use a mounted volume.
.It Fl p , Cm --path Ar PATH
Locate the record for the given path on a mounted filesystem.
.El
.Ss DISK AND VOLUME INFORMATION
By default,
.Nm
will just show you the volume header and quit. Use the following options to get more specific data about the volume and filesystem.
.Bl -tag -offset indent -width "123456789012345"
.It Fl D , Cm --disk-info
Show any available information about the disk, including partitions and volume headers.
.It Fl 0 , Cm --freespace
Show a summary of the used/free space and extent count based on the allocation file. When the
.Fl t
/
.Fl -top
option is added, will list the largest contiguous freespace segments. When the
.Fl v
/
.Fl -verbose
option is added, will list all contiguous freespace segments.
.It Fl s , Cm --summary
Show a summary of the files on the disk. When the
.Fl t
/
.Fl -top
option is added, will list the largest files found.
.It Fl f , Cm --fragmentation
Show a summary of the fragmented files on the disk. When the
.Fl t
/
.Fl -top
option is added, will list the most fragmented files. When the
.Fl v
/
.Fl -verbose
option is added, will list all fragmented files.
.It Fl H , Cm --hotfiles
Show the hottest files on a volume (you must specify the number to list with the
.Fl t
/
.Fl -top
option).
.It Fl t , Cm --top Ar TOP
Specify the number of largest contiguous freespace segments to display (when used with the
.Fl 0
/
.Fl -freespace
option), the number of largest files to display (when used with the
.Fl s
/
.Fl -summary 
option), the number of most fragmented files to display (when used with the
.Fl f
/
.Fl -fragmentation
option), or the number of hottest files to display (when used with the
.Fl H
/
.Fl -hotfiles
option).
.It Fl i , Cm --inspect Ar STARTBLOCK:BLOCKCOUNT
Inspect a block range on a volume and list the files or freespace found within. The
.Ar BLOCKCOUNT
operand is optional, and can be omitted to search to the end of the volume (e.g. 1000000:).
.It Fl r , Cm --volumeheader
Display the HFS Plus volume header.
.It Fl j , Cm --journal
Display the volume's journal structure.
.El
.Ss B-TREE INFORMATION
.Bl -tag -offset indent -width "123456789012345"
.It Fl b , Cm --btree Ar NAME
Specify which HFS+ B-Tree to work with. Supported options: attributes, catalog, extents, or hotfile.
.It Fl n , Cm --node Ar NNUM
Dump an HFS+ B-Tree node by ID (must specify tree with the
.Fl b
/
.Fl -btree
option).
.It Fl T , Cm --type Ar TYPE
Show a list of B-Tree leaf node records of the specified
.Ar TYPE
(must specify tree with the
.Fl b
/
.Fl -btree
option).
.Ar TYPE
should be one of the following:
.Bl -hang indent -width "Attributes B-Tree:"
.It Sy Catalog B-Tree:
"file", "folder", "filethread", "folderthread", or "any"
.It Sy Extents B-Tree:
"extents" or "any"
.It Sy Hotfiles B-Tree:
"hotfile", "hotfilethread", or "any"
.It Sy Attributes B-Tree:
"any"
.El
.Pp
Specifying "any" will list all available record types.
.El
.Ss FILE AND DIRECTORY INFORMATION
.Bl -tag -offset indent -width "123456789012345"
.It Fl c , Cm --cnid Ar CNID
Lookup and display a record by its catalog node ID.
.It Fl F , Cm --fsspec Ar FSSpec
Lookup and display a record by its FSSpec (
.Ar parentCNID:objectName
).
.It Fl l , Cm --list
If the specified FSOB is a folder, list the contents.
.It Fl P , Cm --vol-path Ar PATH
Locate a record by its path on the given device's filesystem.
.It Fl y , Cm --yank Ar DIR
Yank all the filesystem files and put then in the specified directory.
.El
.Ss OUTPUT
You can optionally have
.Nm
dump any fork it finds as the result of an operation. This includes B-Trees or file forks.
Use a command like "-b catalog -o catalog.dump" to extract the catalog file from the boot drive, for instance.
.Bl -tag -offset indent -width "123456789012345"
.It Fl o , Cm --output Ar PATH
Use with 
.Fl b 
or 
.Fl p 
to dump a raw data fork (when used with
.Fl b
, will dump the HFS+ tree file).
.El
.Sh ENVIRONMENT
.Bl -tag -width "NOCOLOR" -offset indent
.It Ev NOCOLOR
Inhibit the use of color in the output (automatically happens when stdout is not a TTY)
.It Ev DEBUG
Feel the firehose.
.El
.\" .Sh FILES
.\" .Bl -tag -width "/usr/local/share/man/man1/hfsinspect.1" -compact
.\" .It Pa /usr/local/bin/hfsinspect
.\" the program
.\" .It Pa /usr/local/share/man/man1/hfsinspect.1
.\" the manpage (this document)
.\" .El
.Sh EXAMPLES
.Nn
.Sh DIAGNOSTICS
.Nn
.\" .Bl -diag
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .It Diagnostic Tag
.\" Diagnostic informtion here.
.\" .El
.Sh COMPATIBILITY
.Nn
.Sh SEE ALSO 
.Xr diskutil 8 ,
.Xr fdisk 8 ,
.Xr gpt 8 , 
.Xr pdisk 8 ,
.Xr hfs.util 8 ,
.Sh STANDARDS
.Rs
.%T "HFS Plus Volume Format"
.%R "Techincal Note TN1150"
.%J "Apple Developer Connection"
.%Q "Apple Computer, Inc."
.%D "Mar 05, 2004"
.%O https://developer.apple.com/legacy/library/technotes/tn/tn1150.html
.Re

.Sh REFERENCES
.Rs
.%T "Secrets of the GPT"
.%R "Techincal Note TN2166"
.%J "Apple Developer Connection"
.%Q "Apple Computer, Inc."
.%D "Nov 06, 2006"
.%O https://developer.apple.com/library/mac/technotes/tn2166/_index.html
.Re

.Rs
.%T "GUID Partition Table"
.%J Wikipedia
.%O https://en.wikipedia.org/wiki/GUID_Partition_Table
.%D "Nov 16, 2013"
.Re

.Rs
.%T "Apple Partition Map"
.%J Wikipedia
.%O https://en.wikipedia.org/wiki/Apple_Partition_Map
.%D "Sep 16, 2013"
.Re

.Sh HISTORY
.Nn
.Sh AUTHOR
.An "Adam Knight" Aq ahknight@pobox.com
.Sh BUGS
Almost certainly, but at least it's read-only.
